USE sakila;

-- Challenge - Joining on multiple tables
-- 1. List the number of films per category.
SELECT
	category.name AS category,
    COUNT(film_category.film_id) AS number_of_films
FROM category
JOIN film_category
	ON category.category_id = film_category.category_id
GROUP BY category.name
ORDER BY number_of_films DESC;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT
	store.store_id,
    city.city,
    country.country
FROM store
    JOIN address
		ON store.address_id = address.address_id
	JOIN city
		ON address.city_id = city.city_id
	JOIN country
		ON city.country_id = country.country_id
    ORDER BY store_id ASC;
    
-- 3.  Calculate the total revenue generated by each store in dollars.
SELECT
	store.store_id,
    FLOOR(SUM(payment.amount)) AS total_revenue
FROM store
	JOIN inventory
		ON store.store_id = inventory.store_id
    JOIN rental
		ON inventory.inventory_id = rental.inventory_id
	JOIN payment
		ON rental.rental_id = payment.rental_id
GROUP BY store.store_id;

-- 4.  Determine the average running time of films for each category.
SELECT
	category.category_id,
    category.name,
    AVG(film.length) AS avg_film_length
FROM category
JOIN film_category
	ON category.category_id = film_category.category_id
JOIN film
	ON film_category.film_id = film.film_id
GROUP BY category.category_id, category.name
ORDER BY category.category_id;
-- I know its unnecessary to show category.category_id AND category.name. But I liked the display better.

-- 5.  Identify the film categories with the longest average running time.
SELECT
	category.category_id,
    category.name,
    AVG(film.length) AS avg_film_length
FROM category
JOIN film_category
	ON category.category_id = film_category.category_id
JOIN film
	ON film_category.film_id = film.film_id
GROUP BY category.category_id, category.name
ORDER BY avg_film_length DESC;

-- 6.  Display the top 10 most frequently rented movies in descending order.
SELECT
	COUNT(rental.rental_id) AS amount_rented,
    film.title
FROM film
JOIN inventory
	ON film.film_id = inventory.film_id
JOIN rental
	ON inventory.inventory_id = rental.inventory_id
GROUP BY film.title
ORDER BY amount_rented DESC
LIMIT 10;

-- 7. Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT
	store.store_id, 
    film.title
FROM store
JOIN inventory
	ON store.store_id = inventory.store_id
JOIN film
	ON inventory.film_id = film.film_id
WHERE
	store.store_id = 1
AND 
	film.title = 'Academy Dinosaur';
-- If it returns rows then the answer is 'Yes'.
-- If it doens't returns any rows the answer is 'No'.

-- 8. Provide a list of all distinct film titles, along with their availability status in the
-- 		inventory. Include a column indicating whether each title is 'Available' or 'NOT available.'
-- 		Note that there are 42 titles that are not in the inventory, and this information can be
-- 		obtained using a `CASE` statement combined with `IFNULL`."
SELECT
	film.title,
	CASE
		WHEN IFNULL(MAX(inventory.inventory_id),0) = 0 THEN 'NOT available'
        ELSE 'Available'
	END AS availability
FROM film
LEFT JOIN inventory
	ON film.film_id = inventory.film_id
GROUP BY film.film_id, film.title
ORDER BY film.title;


















